Select estimated fee UI
witnet/my-wit-wallet pull request #120
Opened 2023-05-04 15:35 UTC by gabaldon

2023-05-04 17:19 UTC, Tommytrg requested changes

2023-05-04 17:19 UTC, Tommytrg commented on pubspec.yaml
> -
We can leave it as it was

2023-05-04 17:19 UTC, Tommytrg commented on macos/Runner.xcodeproj/project.pbxproj
> -			name = Pods;
Is this file part of the build?

2023-05-04 17:19 UTC, Tommytrg commented on lib/widgets/witnet/transactions/value_transfer/create_dialog_box/vtt_builder/02_select_miner_fee.dart
> +  Widget _buildFeeOptionButton(EstimatedFeeOptions label, String value) {
When there is an error, all borders should be red. Right now, one of them is black.

2023-05-05 03:27 UTC, parodyBit commented on lib/bloc/explorer/api_explorer.dart
> +  TransactionCache cache = TransactionCache();
`TransactionCache` is no longer used and we should use the `WalletStorage` from the database.

2023-05-09 10:43 UTC, Tommytrg commented on lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart
> +      AddValueTransferOutputEvent event, Emitter<VTTCreateState> emit) async {
Does this function need to be async?
```suggestion
      AddValueTransferOutputEvent event, Emitter<VTTCreateState> emit) {
```

2023-05-09 13:08 UTC, merged