fix: set preferences after re-import wallet
witnet/my-wit-wallet pull request #236
Opened 2023-06-05 12:34 UTC by parodyBit

Closes #231

2023-06-05 13:54 UTC, Tommytrg commented
@parodyBit Could you run `dart format .`?

2023-06-05 14:10 UTC, Tommytrg commented on lib/util/preferences.dart
> +    if (addressIndex.split('/').first == "0" &&
Could you add a comment explaining what we are checking in this `if` condition?

2023-06-06 16:48 UTC, gabaldon requested changes

2023-06-06 18:16 UTC, Tommytrg commented on lib/bloc/crypto/crypto_bloc.dart
>      await ApiPreferences.setCurrentWallet(_wallet.id);
I see this error in `main` branch but it's solved in this issue. How could we reproduce it?

2023-06-07 07:04 UTC, gabaldon commented on lib/bloc/crypto/crypto_bloc.dart
>      await ApiPreferences.setCurrentWallet(_wallet.id);
My bad, the error is solved in this branch

2023-06-07 07:05 UTC, gabaldon approved these changes

2023-06-07 12:06 UTC, merged