fix: accesibility
witnet/my-wit-wallet pull request #256
Opened 2023-06-20 09:26 UTC by gabaldon

2023-06-20 13:58 UTC, Tommytrg commented on lib/widgets/layouts/dashboard_layout.dart
> +import 'package:flutter/rendering.dart';
```suggestion
```

2023-06-20 13:58 UTC, Tommytrg commented on lib/widgets/layouts/layout.dart
> +import 'package:flutter/rendering.dart';
```suggestion
```

2023-06-22 16:59 UTC, Tommytrg requested changes

2023-06-22 16:59 UTC, Tommytrg commented on lib/theme/extended_theme.dart
> +        focusBg: focusBg ?? this.focusBg);
Are we only adding this two lines here?

2023-06-22 16:59 UTC, Tommytrg commented on lib/shared/api_database.dart
> +
Could we remove this? It's already included in https://github.com/witnet/my-wit-wallet/pull/259
```suggestion
```

2023-06-22 16:59 UTC, Tommytrg commented on lib/shared/api_database.dart
> -    int addressKeyType = int.parse(addressId.split('/').first);
Included in https://github.com/witnet/my-wit-wallet/pull/259

2023-06-22 16:59 UTC, Tommytrg commented on lib/shared/api_database.dart
> -      }
Included in https://github.com/witnet/my-wit-wallet/pull/259

2023-06-23 08:35 UTC, gabaldon commented on lib/main.dart
> +      size: Size(400, 700),
The input error was not completely visible

2023-06-23 14:04 UTC, gabaldon commented on lib/screens/create_wallet/enc_xprv_card.dart
> +                child: IconButton(
Yes, we don't want the default icon color, in this case, it is the sufix of the input and we need to define here the focused style.

2023-06-23 14:40 UTC, merged