(Fix): Update Balance and Wallet Info when switching wallets
witnet/my-wit-wallet pull request #594
Opened 2024-10-16 00:52 UTC by parodyBit

2024-10-21 11:23 UTC, gabaldon requested changes

2024-10-21 11:23 UTC, gabaldon commented on lib/widgets/balance.dart
> +      Wallet currentWallet =
Is it worth it to use a getter for wallet storage?
```WalletStorage get walletStorage => Locator.instance.get<ApiDatabase>().walletStorage;```

```suggestion
            Account currentAccount =
          walletStorage.currentAccount;
      Wallet currentWallet =
          walletStorage.currentWallet;
```

2024-10-21 11:23 UTC, gabaldon commented on lib/widgets/layouts/dashboard_layout.dart
> +          Wallet currentWallet =
Why do we prefer to use the current wallet as a constant within the blocBuilder instead of using a getter?

2024-10-22 17:23 UTC, gabaldon approved these changes

2024-10-22 17:55 UTC, Tommytrg approved these changes
LGTM!

2024-10-23 09:02 UTC, merged